### ISSUE TITLE
按照教程步骤打包报错

### ISSUE THREAD

**Issue by xiyuvi** [zhaoo/hexo-weapp-zhaoo#14]
```
PS E:\hexo-weapp-zhaoo\client> npm run build:weapp

> hexo-weapp-zhaoo@2.0.16 build:weapp
> taro build --type weapp

👽 Taro v3.2.1

C:\Users\Administrator\AppData\Roaming\nvm\v16.14.1\node_modules\@tarojs\cli\node_modules\_resolve@1.15.1@resolve\lib\sync.js:81
    var err = new Error("Cannot find module '" + x + "' from '" + parent + "'");
              ^

Error: Cannot find module '@tarojs/plugin-platform-weapp' from 'E:\hexo-weapp-zhaoo\client'
    at Function.resolveSync [as sync] (C:\Users\Administrator\AppData\Roaming\nvm\v16.14.1\node_modules\@tarojs\cli\node_modules\_resolve@1.15.1@resolve\lib\sync.js:81:15)
    at C:\Users\Administrator\AppData\Roaming\nvm\v16.14.1\node_modules\@tarojs\cli\node_modules\_@tarojs_service@3.2.1@@tarojs\service\dist\utils\index.js:46:31
    at Array.map (<anonymous>)
    at Object.resolvePresetsOrPlugins (C:\Users\Administrator\AppData\Roaming\nvm\v16.14.1\node_modules\@tarojs\cli\node_modules\_@tarojs_service@3.2.1@@tarojs\service\dist\utils\index.js:45:30)
    at Kernel.resolvePlugins (C:\Users\Administrator\AppData\Roaming\nvm\v16.14.1\node_modules\@tarojs\cli\node_modules\_@tarojs_service@3.2.1@@tarojs\service\dist\Kernel.js:90:36)
    at Kernel.initPresetsAndPlugins (C:\Users\Administrator\AppData\Roaming\nvm\v16.14.1\node_modules\@tarojs\cli\node_modules\_@tarojs_service@3.2.1@@tarojs\service\dist\Kernel.js:81:14)
    at Kernel.<anonymous> (C:\Users\Administrator\AppData\Roaming\nvm\v16.14.1\node_modules\@tarojs\cli\node_modules\_@tarojs_service@3.2.1@@tarojs\service\dist\Kernel.js:40:18)
    at Generator.next (<anonymous>)
    at C:\Users\Administrator\AppData\Roaming\nvm\v16.14.1\node_modules\@tarojs\cli\node_modules\_@tarojs_service@3.2.1@@tarojs\service\dist\Kernel.js:8:71
    at new Promise (<anonymous>) {
  code: 'MODULE_NOT_FOUND'
}
PS E:\hexo-weapp-zhaoo\client>
```

请问一下，是不是要在根目录和client目录分别执行npm i，我看教程里没说

**Comment by caozhaoqi** [comment]
肯定是在client里打包
